Test that ninja finishes in one build
I think I've found ~3 cases where it didn't so far, each of which could
cause significant bugs in the output.

diff --git a/build b/build
--- a/build
+++ b/build
@@ -18,6 +18,11 @@ pytest \
   src
 
 ninja
+# TODO: https://github.com/ninja-build/ninja/issues/905 - Remove this hack.
+if [[ "$(ninja -n)" != 'ninja: no work to do.' ]]; then
+  echo 'ERROR: Running ninja a second time is not a no-op.'
+  exit 1
+fi
 ninja -t cleandead
 # TODO: https://github.com/ninja-build/ninja/issues/2617 - Delete this.
 find output work -depth -type d -empty -print -delete
